[2023-03-29 19:43:33,313] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 19:43:42,809] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 19:44:30,895] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 19:47:41,126] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- /home/suyang/projects/software/TRA-project/TRA/backend/backend/constants.py changed, reloading.
[2023-03-29 19:47:42,012] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 19:48:23,119] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:07:51,803] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:08:32,351] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:12:04,249] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:12:27,583] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:16:17,834] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:16:57,954] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:19:02,254] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:19:18,291] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:19:39,592] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:20:10,382] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:20:22,765] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:22:32,973] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:22:58,824] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:23:11,522] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:23:31,471] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:24:20,365] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:24:31,850] [log.py:241] [log:log_response] [WARNING]- Not Found: /
[2023-03-29 20:24:31,850] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 3165
[2023-03-29 20:24:32,002] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2023-03-29 20:24:32,003] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 3216
[2023-03-29 20:48:54,648] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:49:22,500] [log.py:241] [log:log_response] [WARNING]- Not Found: /
[2023-03-29 20:49:22,501] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 3165
[2023-03-29 20:49:22,641] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2023-03-29 20:49:22,641] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 3216
[2023-03-29 20:49:35,705] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /api/core HTTP/1.1" 301 0
[2023-03-29 20:49:35,746] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /api/core/ HTTP/1.1" 200 7918
[2023-03-29 20:49:35,925] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
[2023-03-29 20:49:35,926] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2023-03-29 20:49:35,927] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[2023-03-29 20:49:35,927] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[2023-03-29 20:49:35,928] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[2023-03-29 20:49:35,928] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2023-03-29 20:49:35,934] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[2023-03-29 20:49:35,934] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2023-03-29 20:49:35,934] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[2023-03-29 20:49:35,934] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2023-03-29 20:49:35,938] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2023-03-29 20:49:42,540] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/manager/users/
Traceback (most recent call last):
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'app.response.exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'app'.
[2023-03-29 20:49:42,541] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /api/manager/users/ HTTP/1.1" 500 936446
[2023-03-29 20:49:58,253] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /api/core/ HTTP/1.1" 200 7918
[2023-03-29 20:49:59,653] [basehttp.py:187] [basehttp:log_message] [INFO]- "OPTIONS /api/core/ HTTP/1.1" 200 5691
[2023-03-29 20:50:05,818] [basehttp.py:187] [basehttp:log_message] [INFO]- "OPTIONS /api/core/ HTTP/1.1" 200 5691
[2023-03-29 20:50:07,073] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /api/core/ HTTP/1.1" 200 7918
[2023-03-29 20:50:10,607] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /api/manager/ads/
Traceback (most recent call last):
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "/home/suyang/projects/software/TRA-project/TRA/backend/venv/lib/python3.10/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'app.response.exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'app'.
[2023-03-29 20:50:10,607] [basehttp.py:187] [basehttp:log_message] [ERROR]- "GET /api/manager/ads/ HTTP/1.1" 500 936605
[2023-03-29 20:53:33,086] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:53:37,783] [log.py:241] [log:log_response] [WARNING]- Not Found: /
[2023-03-29 20:53:37,784] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 3165
[2023-03-29 20:53:43,706] [log.py:241] [log:log_response] [WARNING]- Forbidden: /api/manager/users/
[2023-03-29 20:53:43,706] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET /api/manager/users/ HTTP/1.1" 403 5256
[2023-03-29 20:53:53,423] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /api/ HTTP/1.1" 200 5288
[2023-03-29 20:53:59,252] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /api/?format=api HTTP/1.1" 200 5354
[2023-03-29 20:54:03,667] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /api/?format=json HTTP/1.1" 200 54
[2023-03-29 20:54:11,319] [log.py:241] [log:log_response] [WARNING]- Forbidden: /api/manager/ads/
[2023-03-29 20:54:11,319] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET /api/manager/ads/ HTTP/1.1" 403 5292
[2023-03-29 20:55:17,495] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:55:40,012] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2023-03-29 20:55:52,484] [log.py:241] [log:log_response] [WARNING]- Not Found: /
[2023-03-29 20:55:52,484] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET / HTTP/1.1" 404 3165
[2023-03-29 20:55:52,626] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2023-03-29 20:55:52,626] [basehttp.py:187] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 3216
[2023-03-29 20:56:09,172] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /redoc/ HTTP/1.1" 200 930
[2023-03-29 20:56:09,208] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/drf-yasg/redoc-init.js HTTP/1.1" 200 2566
[2023-03-29 20:56:09,208] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
[2023-03-29 20:56:09,209] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
[2023-03-29 20:56:09,223] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/drf-yasg/redoc/redoc.min.js HTTP/1.1" 200 998563
[2023-03-29 20:56:09,491] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /static/drf-yasg/redoc/redoc-logo.png HTTP/1.1" 200 4969
[2023-03-29 20:56:09,572] [basehttp.py:187] [basehttp:log_message] [INFO]- "GET /redoc/?format=openapi HTTP/1.1" 200 104244
[2023-03-29 21:05:31,792] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
